from typing import Optional, Any
from datetime import datetime
from sqlalchemy.orm import Session
from decimal import Decimal

from app.analytics.audit import (
    get_franchise_snapshot,
    get_consolidated_alerts,
    get_cross_domain_signals,
    compare_outlet_domains
)
from app.analytics.service import get_time_series

def _serialize(obj: Any) -> Any:
    if isinstance(obj, Decimal):
        return float(obj)
    if isinstance(obj, dict):
        return {k: _serialize(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_serialize(v) for v in obj]
    if hasattr(obj, 'dict'):
        return _serialize(obj.dict())
    if hasattr(obj, 'model_dump'):
        return _serialize(obj.model_dump())
    return obj

def get_franchise_health_tool(db: Session, start_date: Optional[datetime] = None, end_date: Optional[datetime] = None, outlet_id: Optional[int] = None) -> dict:
    """Retrieve the deterministic franchise-level operational snapshot.
    Use this to get overarching facts like revenue, orders, inventory conditions, workforce metrics, and marketing performance across the business.
    The results represent observed deterministic facts."""
    try:
        if not start_date or not end_date:
            raise ValueError("start_date and end_date are required")
        if start_date > end_date:
            raise ValueError("start_date cannot be after end_date")
        res = get_franchise_snapshot(db, start_date, end_date, outlet_id)
        return {
            "period": {
                "start_date": start_date.isoformat(),
                "end_date": end_date.isoformat()
            },
            "outlet_id": outlet_id,
            "metrics": _serialize(res)
        }
    except Exception as e:
        return {"error": str(e)}

def get_franchise_alerts_tool(db: Session, start_date: Optional[datetime] = None, end_date: Optional[datetime] = None, outlet_id: Optional[int] = None) -> dict:
    """Retrieve consolidated alerts across Outlet Performance, Inventory, Workforce, and Marketing domains.
    Use this to identify which specific issues require operational attention. Alerts are deterministically generated by business rules."""
    try:
        if not start_date or not end_date:
            raise ValueError("start_date and end_date are required")
        if start_date > end_date:
            raise ValueError("start_date cannot be after end_date")
        res = get_consolidated_alerts(db, start_date, end_date, outlet_id)
        return {
            "period": {
                "start_date": start_date.isoformat(),
                "end_date": end_date.isoformat()
            },
            "outlet_id": outlet_id,
            "alerts": _serialize(res)
        }
    except Exception as e:
        return {"error": str(e)}

def get_cross_domain_signals_tool(db: Session, start_date: Optional[datetime] = None, end_date: Optional[datetime] = None, outlet_id: Optional[int] = None) -> dict:
    """Retrieve deterministic cross-domain operational signals identified by the Brew Buzz Audit analytics layer.
    Use this to investigate relationships between demand, outlet performance, inventory conditions, and workforce conditions.
    The results represent observed operational conditions (co-occurrences) and must not be interpreted as proof of causation."""
    try:
        if not start_date or not end_date:
            raise ValueError("start_date and end_date are required")
        if start_date > end_date:
            raise ValueError("start_date cannot be after end_date")
        res = get_cross_domain_signals(db, start_date, end_date, outlet_id)
        return {
            "period": {
                "start_date": start_date.isoformat(),
                "end_date": end_date.isoformat()
            },
            "outlet_id": outlet_id,
            "signals": _serialize(res)
        }
    except Exception as e:
        return {"error": str(e)}

def compare_outlet_domains_tool(db: Session, outlet_id: int, start_date: Optional[datetime] = None, end_date: Optional[datetime] = None) -> dict:
    """Provide cross-domain operational information (Performance, Inventory, Workforce, Marketing) for a specific outlet.
    Use this to get a unified operational matrix of a single outlet's health."""
    try:
        if not start_date or not end_date:
            raise ValueError("start_date and end_date are required")
        if start_date > end_date:
            raise ValueError("start_date cannot be after end_date")
        res = compare_outlet_domains(db, outlet_id, start_date, end_date)
        return {
            "period": {
                "start_date": start_date.isoformat(),
                "end_date": end_date.isoformat()
            },
            "outlet_id": outlet_id,
            "comparison": _serialize(res)
        }
    except ValueError as ve:
        return {"error": str(ve)}
    except Exception as e:
        return {"error": str(e)}

def get_franchise_trends_tool(db: Session, start_date: Optional[datetime] = None, end_date: Optional[datetime] = None, outlet_id: Optional[int] = None) -> dict:
    """Expose supported franchise-level time-series information (daily revenue, orders, AOV).
    Use this to observe the historical trend line of fundamental operational metrics."""
    try:
        if not start_date or not end_date:
            raise ValueError("start_date and end_date are required")
        if start_date > end_date:
            raise ValueError("start_date cannot be after end_date")
        res = get_time_series(db, start_date, end_date, outlet_id)
        return {
            "period": {
                "start_date": start_date.isoformat(),
                "end_date": end_date.isoformat()
            },
            "outlet_id": outlet_id,
            "trends": _serialize(res)
        }
    except Exception as e:
        return {"error": str(e)}
